export const ORDER_PENDING_TO_SHIPPER = 'ORDER_PENDING_TO_SHIPPER';
export const ORDER_ACCEPTED_TO_USER = 'ORDER_ACCEPTED_TO_USER';
// export const NEW_FAVOURITE_USER = 'NEW_FAVOURITE_USER';
// export const USER_CONFIRMS_ASSISTANCE = 'USER_CONFIRMS_ASSISTANCE';
// export const USER_LEFT_INVITATION = 'USER_LEFT_INVITATION';
// export const SUGGESTED_CONTEXT_ACTION = 'SUGGESTED_CONTEXT_ACTION';
// export const SUGGESTED_EVENT = 'SUGGESTED_EVENT';